name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y%m%d-%H%M%S)"

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: scottyak00
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scottyak00/pgdl-competition-image
          path: cuda-tf2-py3
          dockerfile: cuda-tf2-py3/Dockerfile
          tags: ${{ steps.date.outputs.date }}
