name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build cuda-tf2-py3/ --file cuda-tf2-py3/Dockerfile --tag scottyak00/pgdl-competition-image:$(date +%Y%m%d-%H%M%S)
